apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-single
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-single
      version: ">=0.12.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      interval: 1h
  values:
    server:
      persistentVolume:
        enabled: true
        storageClass: cinder-storage
        size: 20Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
