kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-namespace.yaml
  # - postgres-secret.yaml
  # - postgres-init-scripts.yaml

