apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

