apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AEX80UXhhv1UMRC57geGdXB+xJuL+ocUlfQufg==,iv:QxG+MZAicOWDETVVK5elfXmEAVHxCxBLSgNzfyKR3hY=,tag:VeS6KRmkIOz8WXzPQGk/wA==,type:str]
kind: Secret
metadata:
    name: db-secret
    namespace: my-app
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167nhpzxez44rq7ld8mv5erdetsv6nshdcgvh03pkaqncr28f23psgdzwce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaFUvL2s4VXVlQXpaNTBQ
            WjlaZmxIWXdod3ZHOUxjL1plSVFPb2d1MGdnClJzOU5WeEs0OGE0WElDZEVWWkZL
            UEhUcklDQmpic0N4cTEwQVNDcUxqVTgKLS0tIGVlcVhKZGdGNlMrbWovaW1Hc3hu
            ekVJRVBNaVUzZUJ0WE9CLy9IQVdjL0UKZPdLkw3Ly50M3kzZ8inYgV8F3Uhlg6/G
            nlrVWhAmxEWgnhZixLSrQYurGfGYS+JkmR2IDJTtms64LS60MSw8hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T09:54:43Z"
    mac: ENC[AES256_GCM,data:jIOs7s0tPK4VCJRpO23k39N2GtNWQKndyWiL9EOsmZHAgE0FahDfamnk3dW3UFknKwrcs+u0Pu0U/HAfZjk2Fo7Q7TsKEtA8bZQXeO3wa4XTJGOtT7UNkQ05P/cWkmJ0M9nxzHf+E0cqyjmWP2SNAGrifxfSLWx6WKNDal5+wB8=,iv:vNsFcdO+19CIOgsmd/7uAE9LJ0LjnZktBysUD69ZG2M=,tag:B50RvzhWH705400farpnxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
