apiVersion: v1
data:
    password: ENC[AES256_GCM,data:gxKWuLEh/UkTHzQVzxH1lBZAvX+CApkZxjqX5g==,iv:weO8YPLt61cScSvma1Zu6w39jvfBqvI7SZzhuXbvKdI=,tag:go3WQW0mUm6TND8oVpQ2vQ==,type:str]
kind: Secret
metadata:
    name: db-secret
    namespace: my-app
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167nhpzxez44rq7ld8mv5erdetsv6nshdcgvh03pkaqncr28f23psgdzwce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWnRKVG9wRjZCV1A5ZkNm
            eHVBUW90T21yTEFkbERwVHJmbSthVHIyeDFvCkFPSUJCdUYxMHJzZVdFV0hraDZl
            em1Xam1EMFh1N0ZCVzRsWUdRRVcyUVEKLS0tIEtkck1kcUZuQWNBVHFKZ1VOYnRp
            U1FRU1daaHdhMjgydU9BL3hCZmJJRjAKFGzxWZ0bqEZwdKD8mhMb7XZNovF/aTkv
            WBtgUv+5kLVi7WAbxjsMjXxOjmvx7IJ8zvgSnblLuEELAz2L99Q8FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:18:29Z"
    mac: ENC[AES256_GCM,data:QAIsXY8vtkyKp87Lf9vXVhJGAoJAnSdLUQKyZw68gp9o3L2mxCE1z89vCO9RpSlUgkruNUGXbxmUzyqU8yHiAe39jpBZdpH8X1oV8FoTG61HBJw6uWPrigKHGn7XvHeYYvMf/9S8YF/Jk67xDjEsltoqGpwkLZwsnBJNoOpyp88=,iv:qR/QN9UzI6lHUARQUQVW/YdPS6KsrfW3Dd/mYIP2w+0=,tag:VNUCLm7nQ+pzKLUuRbA9lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
