apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: gitops-test
data:
  DB_HOST: "my-app-db.my-app.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "my-app-data"
  DB_USER: "my-app-user"
  DB_POOL_SIZE: "20"
  APP_PORT: "8080"
