apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mariadb-instance.yaml
  - mariadb-database.yaml
  - mariadb-user.yaml
  - mariadb-grant.yaml
  - configmap.yaml
  - app-code-configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - phpmyadmin-deployment.yaml
  - phpmyadmin-service.yaml
  - secrets
