apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: gitops-test
spec:
  selector:
    app.kubernetes.io/name: my-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
